@host = http://localhost:3000
### Create a new class
POST {{host}}/add-classes
Content-Type: application/json

{
  "name": "English",
  "teacher": "Mr. pig",
  "date": "2025-07-05T10:00:00Z"
}

### Get all classes
GET {{host}}/get-all-classes

### Get a class by ID
GET {{host}}/get-class/1

### Update a class by ID
PUT {{host}}/update-class/1
Content-Type: application/json

{
  "name": "Advanced Math",
  "teacher": "Mr. Smith",
  "date": "2025-07-01T10:00:00Z"
}

### Delete a class by ID
DELETE {{host}}/del-class/1
